"""Sunucu hata metinleri — 7 dil (tur 14).

NEDEN: hata zarfindaki `message` alani kullaniciya AYNEN gosterilir (mobil
`ApiException.message`, admin panel hata kutusu). Tur 13'e kadar bu metin
Turkce sabitti; Arapca arayuzde 409 alan bir sakin Turkce cumle goruyordu.

TASARIM — kimlik/metin ayrimi (mobil README §15 ile ayni kural):
  * `APIError` artik CUMLE degil **kimlik** (+ parametre) tasir,
  * metin YALNIZ hata isleyicisinde, istegin `Accept-Language` basligina gore
    uretilir (`errors.py`),
  * dil cozumleme mevcut `ceviri.accept_language_coz` ile AYNI zincirdir
    (icerik cevirisi ve hata metinleri ayni kurali paylasir).

ICERIK CEVIRISI DEGILDIR: buradaki metinler ELLE yazilir, saglayiciya (DeepL
vb.) gonderilmez. Hata metni kisa, sabit ve guvenlik acisindan hassastir;
makine cevirisi hem gereksiz hem ongorulemezdir.

YENI HATA EKLERKEN: `METINLER`e 7 dilin HEPSI yazilir. Eksik dil `test_hata_
i18n.py::test_katalog_tam` ile yakalanir; calisma aninda sessizce Turkce'ye
duser (kullaniciya bos metin gosterilmez).
"""
from __future__ import annotations

from collections.abc import Mapping

from app.ceviri import DESTEKLENEN_DILLER, VARSAYILAN_DIL, accept_language_coz

# --------------------------------------------------------------------------- #
# Cozumleme
# --------------------------------------------------------------------------- #
def istek_dili(accept_language: str | None) -> str:
    """`Accept-Language` -> desteklenen tek dil kodu (yoksa `tr`).

    Icerik cevirisiyle AYNI ayristiriciyi kullanir; boylece bir istek hem
    duyuru metnini hem hata metnini ayni dilde alir.
    """
    for aday in accept_language_coz(accept_language):
        if aday in DESTEKLENEN_DILLER:
            return aday
    return VARSAYILAN_DIL


def hata_metni(
    kimlik: str,
    dil: str = VARSAYILAN_DIL,
    params: Mapping[str, object] | None = None,
) -> str:
    """Kimlik + dil -> kullaniciya gosterilecek metin.

    * Dil eksikse Turkce'ye duser (bos metin ASLA donmez).
    * Kimlik katalogda yoksa kimligin KENDISI doner: yeni bir hata eklenirken
      katalog unutulursa istemci en azindan makine-okunabilir bir sey gorur ve
      testler yakalar. Istegi 500'e cevirmek dogru olmaz.
    * Parametre eksikse ham sablon doner (istek hata isleyicisinde patlamaz).
    """
    diller = METINLER.get(kimlik)
    if diller is None:
        return kimlik
    sablon = diller.get(dil) or diller.get(VARSAYILAN_DIL) or kimlik
    if not params:
        return sablon
    try:
        return sablon.format(**params)
    except (KeyError, IndexError, ValueError):
        return sablon


# --------------------------------------------------------------------------- #
# CEVRILMEYEN metinler (bilincli istisna)
# --------------------------------------------------------------------------- #
# Operator/gelistirici hatalari: yanlis yapilandirma ya da saglayicinin KENDI
# hata metni. Son kullaniciya degil, kuran kisiye/log'a hitap eder; cevirisi
# yaniltici olur ("MinIO yapilandirmasi eksik" mesajini Arapcaya cevirmek
# sorunu cozmez). Bunlar `APIError`e duz metin olarak gecmeye devam eder ve
# `test_hata_i18n.py` bu listeyi kilitler.
CEVRILMEYEN_KODLAR: frozenset[str] = frozenset(
    {
        "storage_unconfigured",     # MinIO/S3 env eksik
        "config_error",             # SDM_KEK vb. sunucu yapilandirmasi
        "payment_unconfigured",     # saglayici anahtarlari eksik
        "payment_provider_error",   # saglayicinin KENDI metni (iyzico/paytr)
        "webhook_unsupported",      # saglayici yetenegi
    }
)


# --------------------------------------------------------------------------- #
# Katalog
# --------------------------------------------------------------------------- #
# Kimlik adlandirmasi: <alan>_<olay> (orn. `daire_bulunamadi`). Sozlesme
# `code`undan AYRIDIR: bir `code` (orn. `conflict`) onlarca kimlige karsilik
# gelir — kod makineye, kimlik metne bakar.
METINLER: dict[str, dict[str, str]] = {
    "kayit_bulunamadi": {
        "tr": "Kayıt bulunamadı.",
        "en": "Record not found.",
        "ar": "لم يتم العثور على السجل.",
        "ru": "Запись не найдена.",
        "de": "Datensatz nicht gefunden.",
        "fr": "Enregistrement introuvable.",
        "es": "Registro no encontrado.",
    },
    "kayit_zaten_mevcut": {
        "tr": "Kayıt zaten mevcut (benzersizlik ihlali).",
        "en": "The record already exists (uniqueness violation).",
        "ar": "السجل موجود بالفعل (انتهاك التفرد).",
        "ru": "Запись уже существует (нарушение уникальности).",
        "de": "Der Datensatz existiert bereits (Eindeutigkeitsverletzung).",
        "fr": "L'enregistrement existe déjà (violation d'unicité).",
        "es": "El registro ya existe (violación de unicidad).",
    },
    "iliskili_kayit_engeli": {
        "tr": "İlişkili kayıt nedeniyle işlem yapılamıyor.",
        "en": "The operation cannot be completed because of a related record.",
        "ar": "تعذّر إتمام العملية بسبب وجود سجل مرتبط.",
        "ru": "Операция невозможна из-за связанной записи.",
        "de": "Der Vorgang ist wegen eines verknüpften Datensatzes nicht möglich.",
        "fr": "Opération impossible en raison d'un enregistrement lié.",
        "es": "No se puede realizar la operación por un registro relacionado.",
    },
    "veritabani_kisit_ihlali": {
        "tr": "Veritabanı kısıt ihlali.",
        "en": "Database constraint violation.",
        "ar": "انتهاك قيد في قاعدة البيانات.",
        "ru": "Нарушение ограничения базы данных.",
        "de": "Verletzung einer Datenbankbedingung.",
        "fr": "Violation d'une contrainte de base de données.",
        "es": "Violación de una restricción de la base de datos.",
    },
    "deger_kisit_ihlali": {
        "tr": "Değer kısıt ihlali.",
        "en": "Value constraint violation.",
        "ar": "انتهاك قيد على القيمة.",
        "ru": "Нарушение ограничения значения.",
        "de": "Verletzung einer Wertebedingung.",
        "fr": "Violation d'une contrainte de valeur.",
        "es": "Violación de una restricción de valor.",
    },
    "zorunlu_alan_eksik": {
        "tr": "Zorunlu alan eksik.",
        "en": "A required field is missing.",
        "ar": "حقل مطلوب مفقود.",
        "ru": "Отсутствует обязательное поле.",
        "de": "Ein Pflichtfeld fehlt.",
        "fr": "Un champ obligatoire est manquant.",
        "es": "Falta un campo obligatorio.",
    },
    "istek_govdesi_gecersiz": {
        "tr": "İstek gövdesi geçersiz.",
        "en": "The request body is invalid.",
        "ar": "نص الطلب غير صالح.",
        "ru": "Тело запроса недействительно.",
        "de": "Der Anfragetext ist ungültig.",
        "fr": "Le corps de la requête est invalide.",
        "es": "El cuerpo de la solicitud no es válido.",
    },
    "idempotency_key_zorunlu": {
        "tr": "Idempotency-Key başlığı zorunludur.",
        "en": "The Idempotency-Key header is required.",
        "ar": "ترويسة Idempotency-Key مطلوبة.",
        "ru": "Заголовок Idempotency-Key обязателен.",
        "de": "Der Header Idempotency-Key ist erforderlich.",
        "fr": "L'en-tête Idempotency-Key est obligatoire.",
        "es": "La cabecera Idempotency-Key es obligatoria.",
    },
    "idempotency_key_govde_farkli": {
        "tr": "Aynı Idempotency-Key farklı gövde ile gönderildi.",
        "en": "The same Idempotency-Key was sent with a different body.",
        "ar": "تم إرسال نفس Idempotency-Key بمحتوى مختلف.",
        "ru": "Тот же Idempotency-Key отправлен с другим телом запроса.",
        "de": "Derselbe Idempotency-Key wurde mit einem anderen Inhalt gesendet.",
        "fr": "La même Idempotency-Key a été envoyée avec un corps différent.",
        "es": "La misma Idempotency-Key se envió con un cuerpo diferente.",
    },
    "kimlik_dogrulama_gerekli": {
        "tr": "Kimlik doğrulama gerekli.",
        "en": "Authentication is required.",
        "ar": "المصادقة مطلوبة.",
        "ru": "Требуется аутентификация.",
        "de": "Authentifizierung erforderlich.",
        "fr": "Authentification requise.",
        "es": "Se requiere autenticación.",
    },
    "access_token_suresi_dolmus": {
        "tr": "Oturum süresi doldu.",
        "en": "Your session has expired.",
        "ar": "انتهت صلاحية جلستك.",
        "ru": "Срок действия сессии истёк.",
        "de": "Ihre Sitzung ist abgelaufen.",
        "fr": "Votre session a expiré.",
        "es": "Su sesión ha caducado.",
    },
    "access_token_gecersiz": {
        "tr": "Geçersiz oturum bilgisi.",
        "en": "Invalid session credentials.",
        "ar": "بيانات جلسة غير صالحة.",
        "ru": "Недействительные данные сессии.",
        "de": "Ungültige Sitzungsdaten.",
        "fr": "Informations de session invalides.",
        "es": "Credenciales de sesión no válidas.",
    },
    "token_tenant_icermiyor": {
        "tr": "Oturum bilgisi tesis kimliği içermiyor.",
        "en": "The session token does not contain a facility ID.",
        "ar": "لا يحتوي رمز الجلسة على معرّف المنشأة.",
        "ru": "Токен сессии не содержит идентификатор объекта.",
        "de": "Das Sitzungstoken enthält keine Anlagen-ID.",
        "fr": "Le jeton de session ne contient pas d'identifiant d'établissement.",
        "es": "El token de sesión no contiene el identificador de la instalación.",
    },
    "kullanici_bulunamadi_veya_pasif": {
        "tr": "Kullanıcı bulunamadı veya pasif.",
        "en": "The user was not found or is inactive.",
        "ar": "المستخدم غير موجود أو غير نشط.",
        "ru": "Пользователь не найден или неактивен.",
        "de": "Benutzer nicht gefunden oder inaktiv.",
        "fr": "Utilisateur introuvable ou inactif.",
        "es": "Usuario no encontrado o inactivo.",
    },
    "refresh_token_gecersiz": {
        "tr": "Geçersiz veya süresi dolmuş oturum yenileme anahtarı.",
        "en": "Invalid or expired refresh token.",
        "ar": "رمز التحديث غير صالح أو منتهي الصلاحية.",
        "ru": "Недействительный или просроченный токен обновления.",
        "de": "Ungültiges oder abgelaufenes Refresh-Token.",
        "fr": "Jeton de rafraîchissement invalide ou expiré.",
        "es": "Token de actualización no válido o caducado.",
    },
    "refresh_token_iptal": {
        "tr": "Oturum yenileme anahtarı geçersiz veya iptal edilmiş.",
        "en": "The refresh token is invalid or has been revoked.",
        "ar": "رمز التحديث غير صالح أو تم إبطاله.",
        "ru": "Токен обновления недействителен или отозван.",
        "de": "Das Refresh-Token ist ungültig oder wurde widerrufen.",
        "fr": "Le jeton de rafraîchissement est invalide ou révoqué.",
        "es": "El token de actualización no es válido o fue revocado.",
    },
    "kurulum_tokeni_gecersiz": {
        "tr": "Geçersiz veya süresi dolmuş kurulum bağlantısı.",
        "en": "Invalid or expired setup link.",
        "ar": "رابط الإعداد غير صالح أو منتهي الصلاحية.",
        "ru": "Недействительная или просроченная ссылка настройки.",
        "de": "Ungültiger oder abgelaufener Einrichtungslink.",
        "fr": "Lien d'installation invalide ou expiré.",
        "es": "Enlace de configuración no válido o caducado.",
    },
    "kurulum_tokeni_kullanilmis": {
        "tr": "Kurulum bağlantısı artık geçerli değil.",
        "en": "The setup link is no longer valid.",
        "ar": "لم يعد رابط الإعداد صالحًا.",
        "ru": "Ссылка настройки больше недействительна.",
        "de": "Der Einrichtungslink ist nicht mehr gültig.",
        "fr": "Le lien d'installation n'est plus valide.",
        "es": "El enlace de configuración ya no es válido.",
    },
    "giris_bilgileri_hatali_email": {
        "tr": "E-posta, parola veya tesis hatalı.",
        "en": "Incorrect e-mail, password or facility.",
        "ar": "البريد الإلكتروني أو كلمة المرور أو المنشأة غير صحيحة.",
        "ru": "Неверный адрес электронной почты, пароль или объект.",
        "de": "E-Mail, Passwort oder Anlage ist falsch.",
        "fr": "E-mail, mot de passe ou établissement incorrect.",
        "es": "Correo electrónico, contraseña o instalación incorrectos.",
    },
    "giris_bilgileri_hatali_telefon": {
        "tr": "Telefon veya parola hatalı.",
        "en": "Incorrect phone number or password.",
        "ar": "رقم الهاتف أو كلمة المرور غير صحيحة.",
        "ru": "Неверный номер телефона или пароль.",
        "de": "Telefonnummer oder Passwort ist falsch.",
        "fr": "Numéro de téléphone ou mot de passe incorrect.",
        "es": "Número de teléfono o contraseña incorrectos.",
    },
    "mevcut_parola_hatali": {
        "tr": "Mevcut parola hatalı.",
        "en": "The current password is incorrect.",
        "ar": "كلمة المرور الحالية غير صحيحة.",
        "ru": "Текущий пароль неверен.",
        "de": "Das aktuelle Passwort ist falsch.",
        "fr": "Le mot de passe actuel est incorrect.",
        "es": "La contraseña actual es incorrecta.",
    },
    "yetkiniz_yok": {
        "tr": "Bu işlem için yetkiniz yok.",
        "en": "You are not authorized to perform this action.",
        "ar": "لا تملك صلاحية تنفيذ هذا الإجراء.",
        "ru": "У вас нет прав для выполнения этого действия.",
        "de": "Sie sind für diese Aktion nicht berechtigt.",
        "fr": "Vous n'êtes pas autorisé à effectuer cette action.",
        "es": "No tiene permiso para realizar esta acción.",
    },
    "daire_bulunamadi": {
        "tr": "Daire bu tesiste bulunamadı.",
        "en": "The unit was not found in this facility.",
        "ar": "لم يتم العثور على الوحدة في هذه المنشأة.",
        "ru": "Квартира не найдена в этом объекте.",
        "de": "Die Wohneinheit wurde in dieser Anlage nicht gefunden.",
        "fr": "Le logement est introuvable dans cet établissement.",
        "es": "No se encontró la vivienda en esta instalación.",
    },
    "daire_tipi_bulunamadi": {
        "tr": "Bağımsız bölüm tipi bulunamadı.",
        "en": "Unit type not found.",
        "ar": "لم يتم العثور على نوع الوحدة.",
        "ru": "Тип помещения не найден.",
        "de": "Einheitentyp nicht gefunden.",
        "fr": "Type de lot introuvable.",
        "es": "No se encontró el tipo de unidad.",
    },
    "daire_grubu_bulunamadi": {
        "tr": "Bağımsız bölüm grubu bulunamadı.",
        "en": "Unit group not found.",
        "ar": "لم يتم العثور على مجموعة الوحدة.",
        "ru": "Группа помещений не найдена.",
        "de": "Einheitengruppe nicht gefunden.",
        "fr": "Groupe de lots introuvable.",
        "es": "No se encontró el grupo de unidades.",
    },
    "hedef_daire_bulunamadi": {
        "tr": "Hedef daire bu tesiste bulunamadı.",
        "en": "The target unit was not found in this facility.",
        "ar": "لم يتم العثور على الوحدة المستهدفة في هذه المنشأة.",
        "ru": "Целевая квартира не найдена в этом объекте.",
        "de": "Die Ziel-Wohneinheit wurde in dieser Anlage nicht gefunden.",
        "fr": "Le logement cible est introuvable dans cet établissement.",
        "es": "No se encontró la vivienda de destino en esta instalación.",
    },
    "daire_listesi_bulunamadi": {
        "tr": "Daire bulunamadı: {eksik}",
        "en": "Unit not found: {eksik}",
        "ar": "لم يتم العثور على الوحدة: {eksik}",
        "ru": "Квартира не найдена: {eksik}",
        "de": "Wohneinheit nicht gefunden: {eksik}",
        "fr": "Logement introuvable : {eksik}",
        "es": "Vivienda no encontrada: {eksik}",
    },
    "daire_no_zaten_kayitli": {
        "tr": "Daire no bu tesiste zaten kayıtlı.",
        "en": "This unit number is already registered in this facility.",
        "ar": "رقم الوحدة مسجّل بالفعل في هذه المنشأة.",
        "ru": "Номер квартиры уже зарегистрирован в этом объекте.",
        "de": "Diese Wohnungsnummer ist in dieser Anlage bereits vergeben.",
        "fr": "Ce numéro de logement est déjà enregistré dans cet établissement.",
        "es": "El número de vivienda ya está registrado en esta instalación.",
    },
    "daire_no_cakismasi": {
        "tr": "Daire no çakışması (eş zamanlı ekleme).",
        "en": "Unit number conflict (concurrent insert).",
        "ar": "تعارض في رقم الوحدة (إضافة متزامنة).",
        "ru": "Конфликт номера квартиры (одновременное добавление).",
        "de": "Konflikt bei der Wohnungsnummer (gleichzeitiges Anlegen).",
        "fr": "Conflit de numéro de logement (ajout simultané).",
        "es": "Conflicto de número de vivienda (alta simultánea).",
    },
    "blok_etiketi_zaten_kayitli": {
        "tr": "Bu blok etiketi bu tesiste zaten kayıtlı.",
        "en": "This block label is already registered in this facility.",
        "ar": "تسمية المبنى هذه مسجّلة بالفعل في هذه المنشأة.",
        "ru": "Такая метка блока уже зарегистрирована в этом объекте.",
        "de": "Diese Blockbezeichnung ist in dieser Anlage bereits vergeben.",
        "fr": "Cette étiquette de bloc est déjà enregistrée dans cet établissement.",
        "es": "Esta etiqueta de bloque ya está registrada en esta instalación.",
    },
    "blok_silme_onayi_gerekli": {
        "tr": "Bu bloğu kullanan {kullanan} daire var; silmek için onay gerekli.",
        "en": "{kullanan} unit(s) use this block; deletion requires confirmation.",
        "ar": "هناك {kullanan} وحدة تستخدم هذا المبنى؛ الحذف يتطلب تأكيدًا.",
        "ru": "Этот блок используют {kullanan} квартир(ы); для удаления нужно подтверждение.",
        "de": "{kullanan} Wohneinheit(en) nutzen diesen Block; das "
            "Löschen erfordert eine Bestätigung.",
        "fr": "{kullanan} logement(s) utilisent ce bloc ; la "
            "suppression requiert une confirmation.",
        "es": "{kullanan} vivienda(s) usan este bloque; la eliminación requiere confirmación.",
    },
    "atanacak_kullanici_resident_olmali": {
        "tr": "Atanacak kullanıcı site sakini olmalı.",
        "en": "The user to be assigned must be a resident.",
        "ar": "يجب أن يكون المستخدم المراد تعيينه من السكان.",
        "ru": "Назначаемый пользователь должен быть жителем.",
        "de": "Der zuzuweisende Benutzer muss Bewohner sein.",
        "fr": "L'utilisateur à affecter doit être un résident.",
        "es": "El usuario que se va a asignar debe ser residente.",
    },
    "kullanici_daireye_zaten_bagli": {
        "tr": "Bu kullanıcı daireye zaten aktif olarak bağlı.",
        "en": "This user is already actively linked to the unit.",
        "ar": "هذا المستخدم مرتبط بالفعل بالوحدة بشكل نشط.",
        "ru": "Этот пользователь уже активно привязан к квартире.",
        "de": "Dieser Benutzer ist der Wohneinheit bereits aktiv zugeordnet.",
        "fr": "Cet utilisateur est déjà lié activement au logement.",
        "es": "Este usuario ya está vinculado activamente a la vivienda.",
    },
    "user_id_bulunamadi": {
        "tr": "Kullanıcı bu tesiste bulunamadı.",
        "en": "The user was not found in this facility.",
        "ar": "لم يتم العثور على المستخدم في هذه المنشأة.",
        "ru": "Пользователь не найден в этом объекте.",
        "de": "Der Benutzer wurde in dieser Anlage nicht gefunden.",
        "fr": "L'utilisateur est introuvable dans cet établissement.",
        "es": "No se encontró el usuario en esta instalación.",
    },
    "aktif_sakin_baglantisi_yok": {
        "tr": "Aktif sakin bağlantısı bulunamadı.",
        "en": "No active resident link was found.",
        "ar": "لم يتم العثور على ارتباط ساكن نشط.",
        "ru": "Активная привязка жителя не найдена.",
        "de": "Keine aktive Bewohnerzuordnung gefunden.",
        "fr": "Aucun lien de résident actif n'a été trouvé.",
        "es": "No se encontró un vínculo de residente activo.",
    },
    "sakin_bulunamadi": {
        "tr": "Sakin bulunamadı.",
        "en": "Resident not found.",
        "ar": "لم يتم العثور على الساكن.",
        "ru": "Житель не найден.",
        "de": "Bewohner nicht gefunden.",
        "fr": "Résident introuvable.",
        "es": "Residente no encontrado.",
    },
    "telefon_veya_email_zaten_kayitli": {
        "tr": "Bu telefon veya e-posta zaten kayıtlı.",
        "en": "This phone number or e-mail is already registered.",
        "ar": "رقم الهاتف أو البريد الإلكتروني مسجّل بالفعل.",
        "ru": "Этот телефон или адрес электронной почты уже зарегистрирован.",
        "de": "Diese Telefonnummer oder E-Mail-Adresse ist bereits registriert.",
        "fr": "Ce numéro de téléphone ou cet e-mail est déjà enregistré.",
        "es": "Este teléfono o correo electrónico ya está registrado.",
    },
    "telefon_zaten_kayitli": {
        "tr": "Bu telefon zaten kayıtlı.",
        "en": "This phone number is already registered.",
        "ar": "رقم الهاتف هذا مسجّل بالفعل.",
        "ru": "Этот номер телефона уже зарегистрирован.",
        "de": "Diese Telefonnummer ist bereits registriert.",
        "fr": "Ce numéro de téléphone est déjà enregistré.",
        "es": "Este número de teléfono ya está registrado.",
    },
    "telefon_birden_fazla_yoneticide": {
        "tr": "Aynı telefon birden fazla yöneticide kullanılamaz.",
        "en": "The same phone number cannot be used by more than one manager.",
        "ar": "لا يمكن استخدام نفس رقم الهاتف لأكثر من مدير.",
        "ru": "Один и тот же номер телефона не может использоваться несколькими управляющими.",
        "de": "Dieselbe Telefonnummer kann nicht von mehreren Verwaltern verwendet werden.",
        "fr": "Le même numéro de téléphone ne peut pas être utilisé par plusieurs gestionnaires.",
        "es": "El mismo teléfono no puede usarse en más de un administrador.",
    },
    "telefon_gecersiz": {
        "tr": "Geçersiz telefon numarası.",
        "en": "Invalid phone number.",
        "ar": "رقم هاتف غير صالح.",
        "ru": "Недействительный номер телефона.",
        "de": "Ungültige Telefonnummer.",
        "fr": "Numéro de téléphone invalide.",
        "es": "Número de teléfono no válido.",
    },
    "rol_olusturulamaz_yalniz_saha": {
        "tr": "Bu rolü oluşturamazsınız (yalnız güvenlik/tesis görevlisi).",
        "en": "You cannot create this role (security/facility staff only).",
        "ar": "لا يمكنك إنشاء هذا الدور (الأمن/موظف المنشأة فقط).",
        "ru": "Вы не можете создать эту роль (только охрана/сотрудник объекта).",
        "de": "Sie können diese Rolle nicht anlegen (nur Sicherheits-/Anlagenpersonal).",
        "fr": "Vous ne pouvez pas créer ce rôle (agent de sécurité/technique uniquement).",
        "es": "No puede crear este rol (solo seguridad/personal de la instalación).",
    },
    "rol_yalniz_saha_yapilabilir": {
        "tr": "Rolü yalnız güvenlik/tesis görevlisi yapabilirsiniz.",
        "en": "You can only set the role to security/facility staff.",
        "ar": "يمكنك تعيين الدور إلى الأمن/موظف المنشأة فقط.",
        "ru": "Вы можете назначить только роль охраны/сотрудника объекта.",
        "de": "Sie können die Rolle nur auf Sicherheits-/Anlagenpersonal setzen.",
        "fr": "Vous ne pouvez attribuer que le rôle d'agent de sécurité/technique.",
        "es": "Solo puede asignar el rol de seguridad/personal de la instalación.",
    },
    "yalniz_saha_personeli_duzenlenir": {
        "tr": "Yalnız saha personelini düzenleyebilirsiniz.",
        "en": "You can only edit field staff.",
        "ar": "يمكنك تعديل الموظفين الميدانيين فقط.",
        "ru": "Вы можете редактировать только полевой персонал.",
        "de": "Sie können nur Außendienstpersonal bearbeiten.",
        "fr": "Vous ne pouvez modifier que le personnel de terrain.",
        "es": "Solo puede editar al personal de campo.",
    },
    "yalniz_saha_personeli_parola": {
        "tr": "Yalnız saha personelinin parolasını sıfırlayabilirsiniz.",
        "en": "You can only reset the password of field staff.",
        "ar": "يمكنك إعادة تعيين كلمة مرور الموظفين الميدانيين فقط.",
        "ru": "Вы можете сбросить пароль только полевому персоналу.",
        "de": "Sie können nur das Passwort von Außendienstpersonal zurücksetzen.",
        "fr": "Vous ne pouvez réinitialiser que le mot de passe du personnel de terrain.",
        "es": "Solo puede restablecer la contraseña del personal de campo.",
    },
    "yalniz_saha_personeline_foto": {
        "tr": "Yalnız saha personeline fotoğraf atanabilir.",
        "en": "A photo can only be assigned to field staff.",
        "ar": "لا يمكن إسناد صورة إلا للموظفين الميدانيين.",
        "ru": "Фотографию можно назначить только полевому персоналу.",
        "de": "Ein Foto kann nur Außendienstpersonal zugewiesen werden.",
        "fr": "Une photo ne peut être attribuée qu'au personnel de terrain.",
        "es": "Solo se puede asignar una foto al personal de campo.",
    },
    "tesiste_yonetici_yok": {
        "tr": "Tesiste yönetici yok.",
        "en": "The facility has no manager.",
        "ar": "لا يوجد مدير في المنشأة.",
        "ru": "В объекте нет управляющего.",
        "de": "Die Anlage hat keinen Verwalter.",
        "fr": "L'établissement n'a pas de gestionnaire.",
        "es": "La instalación no tiene administrador.",
    },
    "tenant_bulunamadi": {
        "tr": "Tesis bulunamadı.",
        "en": "Facility not found.",
        "ar": "لم يتم العثور على المنشأة.",
        "ru": "Объект не найден.",
        "de": "Anlage nicht gefunden.",
        "fr": "Établissement introuvable.",
        "es": "Instalación no encontrada.",
    },
    "tesis_zaten_kuruldu": {
        "tr": "Tesis zaten kuruldu.",
        "en": "The facility has already been set up.",
        "ar": "تم إعداد المنشأة بالفعل.",
        "ru": "Объект уже настроен.",
        "de": "Die Anlage wurde bereits eingerichtet.",
        "fr": "L'établissement est déjà configuré.",
        "es": "La instalación ya está configurada.",
    },
    "tesis_adi_yalniz_birincil_yonetici": {
        "tr": "Tesisi yalnız birincil yönetici adlandırabilir.",
        "en": "Only the primary manager can name the facility.",
        "ar": "يمكن للمدير الرئيسي فقط تسمية المنشأة.",
        "ru": "Назвать объект может только главный управляющий.",
        "de": "Nur der Hauptverwalter kann die Anlage benennen.",
        "fr": "Seul le gestionnaire principal peut nommer l'établissement.",
        "es": "Solo el administrador principal puede nombrar la instalación.",
    },
    "yonetici_sinirli_alan_degistirir": {
        "tr": "Yönetici yalnız tesis adını ve hava konumunu değiştirebilir.",
        "en": "A manager can only change the facility name and the weather location.",
        "ar": "يمكن للمدير تغيير اسم المنشأة وموقع الطقس فقط.",
        "ru": "Управляющий может изменить только название объекта и место для погоды.",
        "de": "Ein Verwalter kann nur den Anlagennamen und den Wetterort ändern.",
        "fr": "Un gestionnaire ne peut modifier que le nom de l'établissement et le lieu météo.",
        "es": "Un administrador solo puede cambiar el nombre de la "
            "instalación y la ubicación del tiempo.",
    },
    "atanan_user_bulunamadi": {
        "tr": "Atanacak kullanıcı bu tesiste bulunamadı.",
        "en": "The user to be assigned was not found in this facility.",
        "ar": "لم يتم العثور على المستخدم المراد تعيينه في هذه المنشأة.",
        "ru": "Назначаемый пользователь не найден в этом объекте.",
        "de": "Der zuzuweisende Benutzer wurde in dieser Anlage nicht gefunden.",
        "fr": "L'utilisateur à affecter est introuvable dans cet établissement.",
        "es": "No se encontró en esta instalación al usuario que se va a asignar.",
    },
    "gorev_atama_rol_kisiti": {
        "tr": "Yönetici görevi yalnız güvenlik/tesis görevlisi kullanıcılara atayabilir.",
        "en": "A manager can only assign tasks to security/facility staff.",
        "ar": "لا يمكن للمدير إسناد المهام إلا لموظفي الأمن/المنشأة.",
        "ru": "Управляющий может назначать задачи только охране/сотрудникам объекта.",
        "de": "Ein Verwalter kann Aufgaben nur Sicherheits-/Anlagenpersonal zuweisen.",
        "fr": "Un gestionnaire ne peut affecter des tâches qu'au personnel de sécurité/technique.",
        "es": "Un administrador solo puede asignar tareas a seguridad/personal de la instalación.",
    },
    "gorev_pasif_kategoriye_yazilamaz": {
        "tr": "Pasif kategoriye görev yazılamaz (kategori silinmiş).",
        "en": "Tasks cannot be created in an inactive category (the category was deleted).",
        "ar": "لا يمكن إنشاء مهام في فئة غير نشطة (تم حذف الفئة).",
        "ru": "Нельзя создать задачу в неактивной категории (категория удалена).",
        "de": "In einer inaktiven Kategorie können keine Aufgaben "
            "angelegt werden (Kategorie gelöscht).",
        "fr": "Impossible de créer une tâche dans une catégorie inactive (catégorie supprimée).",
        "es": "No se pueden crear tareas en una categoría inactiva (la categoría fue eliminada).",
    },
    "gorev_yalniz_atanan_tamamlar": {
        "tr": "Bu görevi yalnız atanan kullanıcı tamamlayabilir.",
        "en": "Only the assigned user can complete this task.",
        "ar": "لا يمكن إنهاء هذه المهمة إلا من قبل المستخدم المُسنَدة إليه.",
        "ru": "Завершить эту задачу может только назначенный пользователь.",
        "de": "Nur der zugewiesene Benutzer kann diese Aufgabe abschließen.",
        "fr": "Seul l'utilisateur affecté peut terminer cette tâche.",
        "es": "Solo el usuario asignado puede completar esta tarea.",
    },
    "gorev_foto_kaniti_zorunlu": {
        "tr": "Bu görev için fotoğraf kanıtı zorunlu.",
        "en": "Photo evidence is required for this task.",
        "ar": "إثبات بالصورة مطلوب لهذه المهمة.",
        "ru": "Для этой задачи требуется фотоподтверждение.",
        "de": "Für diese Aufgabe ist ein Fotonachweis erforderlich.",
        "fr": "Une preuve photo est obligatoire pour cette tâche.",
        "es": "Se requiere evidencia fotográfica para esta tarea.",
    },
    "gorev_nfc_eslesmiyor": {
        "tr": "Okutulan etiket görevin kontrol noktasıyla eşleşmiyor.",
        "en": "The scanned tag does not match the task's checkpoint.",
        "ar": "البطاقة الممسوحة لا تطابق نقطة تفتيش المهمة.",
        "ru": "Отсканированная метка не соответствует контрольной точке задачи.",
        "de": "Das gescannte Tag passt nicht zum Kontrollpunkt der Aufgabe.",
        "fr": "Le tag scanné ne correspond pas au point de contrôle de la tâche.",
        "es": "La etiqueta escaneada no coincide con el punto de control de la tarea.",
    },
    "kategori_adi_zaten_kayitli": {
        "tr": "Bu adla kategori zaten kayıtlı.",
        "en": "A category with this name already exists.",
        "ar": "توجد فئة بهذا الاسم بالفعل.",
        "ru": "Категория с таким названием уже существует.",
        "de": "Eine Kategorie mit diesem Namen existiert bereits.",
        "fr": "Une catégorie portant ce nom existe déjà.",
        "es": "Ya existe una categoría con ese nombre.",
    },
    "kategori_id_bicimi": {
        "tr": "kategori_id, UUID veya 'diger' olmalı.",
        "en": "kategori_id must be a UUID or 'diger'.",
        "ar": "يجب أن يكون kategori_id معرّف UUID أو 'diger'.",
        "ru": "kategori_id должен быть UUID или 'diger'.",
        "de": "kategori_id muss eine UUID oder 'diger' sein.",
        "fr": "kategori_id doit être un UUID ou 'diger'.",
        "es": "kategori_id debe ser un UUID o 'diger'.",
    },
    "atanan_user_id_bicimi": {
        "tr": "atanan_user_id, 'me' veya UUID olmalı.",
        "en": "atanan_user_id must be 'me' or a UUID.",
        "ar": "يجب أن يكون atanan_user_id إما 'me' أو معرّف UUID.",
        "ru": "atanan_user_id должен быть 'me' или UUID.",
        "de": "atanan_user_id muss 'me' oder eine UUID sein.",
        "fr": "atanan_user_id doit être 'me' ou un UUID.",
        "es": "atanan_user_id debe ser 'me' o un UUID.",
    },
    "talep_atanan_rol_kisiti": {
        "tr": "Atanan kişi güvenlik veya tesis görevlisi olmalı.",
        "en": "The assignee must be security or facility staff.",
        "ar": "يجب أن يكون المُسنَد إليه من الأمن أو موظفي المنشأة.",
        "ru": "Исполнителем должен быть сотрудник охраны или объекта.",
        "de": "Die zugewiesene Person muss Sicherheits- oder Anlagenpersonal sein.",
        "fr": "La personne affectée doit être agent de sécurité ou technique.",
        "es": "La persona asignada debe ser de seguridad o personal de la instalación.",
    },
    "vardiya_atama_rol_kisiti": {
        "tr": "Yalnız güvenlik/tesis görevlisi kullanıcıları atanabilir.",
        "en": "Only security/facility staff users can be assigned.",
        "ar": "لا يمكن إسناد المهمة إلا لمستخدمي الأمن/موظفي المنشأة.",
        "ru": "Назначать можно только сотрудников охраны/объекта.",
        "de": "Es können nur Sicherheits-/Anlagenpersonal zugewiesen werden.",
        "fr": "Seuls les agents de sécurité/techniques peuvent être affectés.",
        "es": "Solo se puede asignar a usuarios de seguridad/personal de la instalación.",
    },
    "checkpoint_bulunamadi": {
        "tr": "Kontrol noktası bu tesiste bulunamadı.",
        "en": "The checkpoint was not found in this facility.",
        "ar": "لم يتم العثور على نقطة التفتيش في هذه المنشأة.",
        "ru": "Контрольная точка не найдена в этом объекте.",
        "de": "Der Kontrollpunkt wurde in dieser Anlage nicht gefunden.",
        "fr": "Le point de contrôle est introuvable dans cet établissement.",
        "es": "No se encontró el punto de control en esta instalación.",
    },
    "checkpoint_listesi_bulunamadi": {
        "tr": "Kontrol noktası bu tesiste bulunamadı: {eksik}",
        "en": "Checkpoint not found in this facility: {eksik}",
        "ar": "نقطة التفتيش غير موجودة في هذه المنشأة: {eksik}",
        "ru": "Контрольная точка не найдена в этом объекте: {eksik}",
        "de": "Kontrollpunkt in dieser Anlage nicht gefunden: {eksik}",
        "fr": "Point de contrôle introuvable dans cet établissement : {eksik}",
        "es": "Punto de control no encontrado en esta instalación: {eksik}",
    },
    "shift_bulunamadi": {
        "tr": "Vardiya bu tesiste bulunamadı.",
        "en": "The shift was not found in this facility.",
        "ar": "لم يتم العثور على الوردية في هذه المنشأة.",
        "ru": "Смена не найдена в этом объекте.",
        "de": "Die Schicht wurde in dieser Anlage nicht gefunden.",
        "fr": "Le poste est introuvable dans cet établissement.",
        "es": "No se encontró el turno en esta instalación.",
    },
    "plan_tekrar_eden_sira": {
        "tr": "Tekrar eden sıra: {sira}",
        "en": "Duplicate order number: {sira}",
        "ar": "رقم ترتيب مكرر: {sira}",
        "ru": "Повторяющийся порядковый номер: {sira}",
        "de": "Doppelte Reihenfolge: {sira}",
        "fr": "Ordre en double : {sira}",
        "es": "Orden duplicado: {sira}",
    },
    "plan_tekrar_eden_checkpoint": {
        "tr": "Tekrar eden kontrol noktası: {checkpoint}",
        "en": "Duplicate checkpoint: {checkpoint}",
        "ar": "نقطة تفتيش مكررة: {checkpoint}",
        "ru": "Повторяющаяся контрольная точка: {checkpoint}",
        "de": "Doppelter Kontrollpunkt: {checkpoint}",
        "fr": "Point de contrôle en double : {checkpoint}",
        "es": "Punto de control duplicado: {checkpoint}",
    },
    "patrol_window_bulunamadi": {
        "tr": "Tur penceresi bu tesiste bulunamadı.",
        "en": "The patrol window was not found in this facility.",
        "ar": "لم يتم العثور على نافذة الجولة في هذه المنشأة.",
        "ru": "Окно обхода не найдено в этом объекте.",
        "de": "Das Rundgangsfenster wurde in dieser Anlage nicht gefunden.",
        "fr": "La fenêtre de ronde est introuvable dans cet établissement.",
        "es": "No se encontró la ventana de ronda en esta instalación.",
    },
    "nfc_checkpoint_eslesmedi": {
        "tr": "Okutulan etiket hiçbir kontrol noktasıyla eşleşmedi.",
        "en": "The scanned tag did not match any checkpoint.",
        "ar": "البطاقة الممسوحة لا تطابق أي نقطة تفتيش.",
        "ru": "Отсканированная метка не соответствует ни одной контрольной точке.",
        "de": "Das gescannte Tag passt zu keinem Kontrollpunkt.",
        "fr": "Le tag scanné ne correspond à aucun point de contrôle.",
        "es": "La etiqueta escaneada no coincide con ningún punto de control.",
    },
    "checkpoint_nfc_eslesmiyor": {
        "tr": "Kontrol noktası okutulan etiketle eşleşmiyor.",
        "en": "The checkpoint does not match the scanned tag.",
        "ar": "نقطة التفتيش لا تطابق البطاقة الممسوحة.",
        "ru": "Контрольная точка не соответствует отсканированной метке.",
        "de": "Der Kontrollpunkt passt nicht zum gescannten Tag.",
        "fr": "Le point de contrôle ne correspond pas au tag scanné.",
        "es": "El punto de control no coincide con la etiqueta escaneada.",
    },
    "sdm_alanlari_birlikte_gonderilmeli": {
        "tr": "sdm_picc_data ve sdm_cmac birlikte gönderilmeli.",
        "en": "sdm_picc_data and sdm_cmac must be sent together.",
        "ar": "يجب إرسال sdm_picc_data و sdm_cmac معًا.",
        "ru": "sdm_picc_data и sdm_cmac должны отправляться вместе.",
        "de": "sdm_picc_data und sdm_cmac müssen zusammen gesendet werden.",
        "fr": "sdm_picc_data et sdm_cmac doivent être envoyés ensemble.",
        "es": "sdm_picc_data y sdm_cmac deben enviarse juntos.",
    },
    "sdm_imza_dogrulanamadi": {
        "tr": "Etiket imzası doğrulanamadı.",
        "en": "The tag signature could not be verified.",
        "ar": "تعذّر التحقق من توقيع البطاقة.",
        "ru": "Не удалось проверить подпись метки.",
        "de": "Die Tag-Signatur konnte nicht verifiziert werden.",
        "fr": "La signature du tag n'a pas pu être vérifiée.",
        "es": "No se pudo verificar la firma de la etiqueta.",
    },
    "sdm_tekrar_oynatma": {
        "tr": "Etiket okuma sayacı ilerlememiş (tekrar oynatma).",
        "en": "The tag read counter did not advance (replay detected).",
        "ar": "لم يتقدّم عدّاد قراءة البطاقة (إعادة تشغيل).",
        "ru": "Счётчик считываний метки не увеличился (повтор).",
        "de": "Der Lesezähler des Tags wurde nicht erhöht (Replay).",
        "fr": "Le compteur de lecture du tag n'a pas progressé (rejeu).",
        "es": "El contador de lectura de la etiqueta no avanzó (repetición).",
    },
    "demirbas_nfc_eslesmiyor": {
        "tr": "Okutulan etiket demirbaş ile eşleşmiyor.",
        "en": "The scanned tag does not match the asset.",
        "ar": "البطاقة الممسوحة لا تطابق العهدة.",
        "ru": "Отсканированная метка не соответствует активу.",
        "de": "Das gescannte Tag passt nicht zum Inventar.",
        "fr": "Le tag scanné ne correspond pas à l'équipement.",
        "es": "La etiqueta escaneada no coincide con el activo.",
    },
    "nfc_uid_zaten_kayitli": {
        "tr": "Bu etiket bu tesiste zaten kayıtlı.",
        "en": "This tag is already registered in this facility.",
        "ar": "هذه البطاقة مسجّلة بالفعل في هذه المنشأة.",
        "ru": "Эта метка уже зарегистрирована в этом объекте.",
        "de": "Dieses Tag ist in dieser Anlage bereits registriert.",
        "fr": "Ce tag est déjà enregistré dans cet établissement.",
        "es": "Esta etiqueta ya está registrada en esta instalación.",
    },
    "checked_out_by_bicimi": {
        "tr": "checked_out_by, 'me' veya UUID olmalı.",
        "en": "checked_out_by must be 'me' or a UUID.",
        "ar": "يجب أن يكون checked_out_by إما 'me' أو معرّف UUID.",
        "ru": "checked_out_by должен быть 'me' или UUID.",
        "de": "checked_out_by muss 'me' oder eine UUID sein.",
        "fr": "checked_out_by doit être 'me' ou un UUID.",
        "es": "checked_out_by debe ser 'me' o un UUID.",
    },
    "checked_out_by_yalniz_admin": {
        "tr": "Başka bir kullanıcı adına sorgulama yalnız yöneticiye açıktır; 'me' kullanın.",
        "en": "Querying on behalf of another user is admin-only; use 'me'.",
        "ar": "الاستعلام نيابةً عن مستخدم آخر متاح للمشرف فقط؛ استخدم 'me'.",
        "ru": "Запрос от имени другого пользователя доступен только "
            "администратору; используйте 'me'.",
        "de": "Abfragen im Namen anderer Benutzer sind nur für "
            "Administratoren; verwenden Sie 'me'.",
        "fr": "Interroger au nom d'un autre utilisateur est réservé "
            "à l'administrateur ; utilisez 'me'.",
        "es": "Consultar en nombre de otro usuario es solo para administradores; use 'me'.",
    },
    "demirbas_zaten_zimmetli": {
        "tr": "Demirbaş zaten zimmetli.",
        "en": "The asset is already checked out.",
        "ar": "العهدة مُسلَّمة بالفعل.",
        "ru": "Актив уже выдан.",
        "de": "Das Inventar ist bereits ausgegeben.",
        "fr": "L'équipement est déjà attribué.",
        "es": "El activo ya está asignado.",
    },
    "demirbas_acik_zimmet_yok": {
        "tr": "Açık zimmet yok (demirbaş zaten müsait).",
        "en": "There is no open checkout (the asset is already available).",
        "ar": "لا توجد عهدة مفتوحة (العهدة متاحة بالفعل).",
        "ru": "Нет активной выдачи (актив уже доступен).",
        "de": "Keine offene Ausgabe (das Inventar ist bereits verfügbar).",
        "fr": "Aucune attribution en cours (l'équipement est déjà disponible).",
        "es": "No hay entrega abierta (el activo ya está disponible).",
    },
    "demirbas_baskasinin_zimmetinde": {
        "tr": "Zimmet başkasının üzerinde; yalnız sahibi veya yönetici bırakabilir.",
        "en": "The asset is checked out to someone else; only the "
            "holder or an admin can return it.",
        "ar": "العهدة مسجّلة على شخص آخر؛ لا يمكن إرجاعها إلا من حاملها أو المشرف.",
        "ru": "Актив выдан другому лицу; вернуть может только держатель или администратор.",
        "de": "Das Inventar ist einer anderen Person zugeordnet; nur der "
            "Inhaber oder ein Administrator kann es zurückgeben.",
        "fr": "L'équipement est attribué à quelqu'un d'autre ; seul le "
            "détenteur ou un administrateur peut le rendre.",
        "es": "El activo está asignado a otra persona; solo el titular "
            "o un administrador puede devolverlo.",
    },
    "goruntuleme_izni_yok": {
        "tr": "Bu daire için geçerli (kullanılmamış) görüntüleme izniniz yok.",
        "en": "You do not have a valid (unused) view permission for this unit.",
        "ar": "ليس لديك إذن عرض صالح (غير مستخدَم) لهذه الوحدة.",
        "ru": "У вас нет действующего (неиспользованного) разрешения на просмотр этой квартиры.",
        "de": "Sie haben keine gültige (unbenutzte) Anzeigeberechtigung für diese Wohneinheit.",
        "fr": "Vous n'avez pas d'autorisation de consultation "
            "valide (non utilisée) pour ce logement.",
        "es": "No tiene un permiso de consulta válido (sin usar) para esta vivienda.",
    },
    "kayit_yonetime_kapali": {
        "tr": "Bu kayıt yönetime kapalı; daire için tek seferlik izin alın.",
        "en": "This record is not open to management; obtain a one-time permission for the unit.",
        "ar": "هذا السجل غير متاح للإدارة؛ احصل على إذن لمرة واحدة للوحدة.",
        "ru": "Эта запись закрыта для управляющей компании; "
            "получите разовое разрешение для квартиры.",
        "de": "Dieser Datensatz ist für die Verwaltung gesperrt; holen Sie eine "
            "einmalige Berechtigung für die Wohneinheit ein.",
        "fr": "Cet enregistrement est fermé à la gestion ; obtenez une "
            "autorisation ponctuelle pour le logement.",
        "es": "Este registro está cerrado a la administración; obtenga "
            "un permiso puntual para la vivienda.",
    },
    "kargo_yonetime_kapali": {
        "tr": "Kargo kayıtları yönetime kapalı; bir daire için tek seferlik izin alın.",
        "en": "Parcel records are not open to management; obtain a one-time permission for a unit.",
        "ar": "سجلات الطرود غير متاحة للإدارة؛ احصل على إذن لمرة واحدة لوحدة معيّنة.",
        "ru": "Записи о посылках закрыты для управляющей компании; "
            "получите разовое разрешение для квартиры.",
        "de": "Paketdatensätze sind für die Verwaltung gesperrt; holen Sie eine "
            "einmalige Berechtigung für eine Wohneinheit ein.",
        "fr": "Les enregistrements de colis sont fermés à la gestion ; obtenez "
            "une autorisation ponctuelle pour un logement.",
        "es": "Los registros de paquetes están cerrados a la administración; "
            "obtenga un permiso puntual para una vivienda.",
    },
    "ziyaretci_yonetime_kapali": {
        "tr": "Ziyaretçi kayıtları yönetime kapalı; bir daire için tek seferlik izin alın.",
        "en": "Visitor records are not open to management; obtain "
            "a one-time permission for a unit.",
        "ar": "سجلات الزوار غير متاحة للإدارة؛ احصل على إذن لمرة واحدة لوحدة معيّنة.",
        "ru": "Записи о посетителях закрыты для управляющей компании; "
            "получите разовое разрешение для квартиры.",
        "de": "Besucherdatensätze sind für die Verwaltung gesperrt; holen Sie eine "
            "einmalige Berechtigung für eine Wohneinheit ein.",
        "fr": "Les enregistrements de visiteurs sont fermés à la gestion ; "
            "obtenez une autorisation ponctuelle pour un logement.",
        "es": "Los registros de visitantes están cerrados a la administración; "
            "obtenga un permiso puntual para una vivienda.",
    },
    "kargo_zaten_teslim_alinmis": {
        "tr": "Kargo zaten teslim alınmış.",
        "en": "The parcel has already been picked up.",
        "ar": "تم استلام الطرد بالفعل.",
        "ru": "Посылка уже получена.",
        "de": "Das Paket wurde bereits abgeholt.",
        "fr": "Le colis a déjà été récupéré.",
        "es": "El paquete ya fue recogido.",
    },
    "hedef_sakin_daire_disi": {
        "tr": "Seçilen kişi bu dairenin aktif sakini değil.",
        "en": "The selected person is not an active resident of this unit.",
        "ar": "الشخص المحدد ليس ساكنًا نشطًا في هذه الوحدة.",
        "ru": "Выбранный человек не является активным жителем этой квартиры.",
        "de": "Die ausgewählte Person ist kein aktiver Bewohner dieser Wohneinheit.",
        "fr": "La personne sélectionnée n'est pas un résident actif de ce logement.",
        "es": "La persona seleccionada no es residente activo de esta vivienda.",
    },
    "ziyaretci_cikisi_zaten_kayitli": {
        "tr": "Ziyaretçi çıkışı zaten kaydedilmiş.",
        "en": "The visitor's exit has already been recorded.",
        "ar": "تم تسجيل خروج الزائر بالفعل.",
        "ru": "Выход посетителя уже зарегистрирован.",
        "de": "Der Austritt des Besuchers wurde bereits erfasst.",
        "fr": "La sortie du visiteur a déjà été enregistrée.",
        "es": "La salida del visitante ya fue registrada.",
    },
    "giris_zamani_gelecekte": {
        "tr": "Giriş zamanı gelecekte olamaz.",
        "en": "The entry time cannot be in the future.",
        "ar": "لا يمكن أن يكون وقت الدخول في المستقبل.",
        "ru": "Время въезда не может быть в будущем.",
        "de": "Die Einfahrtszeit darf nicht in der Zukunft liegen.",
        "fr": "L'heure d'entrée ne peut pas être dans le futur.",
        "es": "La hora de entrada no puede estar en el futuro.",
    },
    "arac_acik_gecisi_var": {
        "tr": "{plaka} plakalı aracın açık bir geçişi var (araç içeride).",
        "en": "The vehicle with plate {plaka} has an open pass (the vehicle is inside).",
        "ar": "المركبة ذات اللوحة {plaka} لديها تصريح مفتوح (المركبة بالداخل).",
        "ru": "У автомобиля с номером {plaka} есть открытый проезд (автомобиль внутри).",
        "de": "Das Fahrzeug mit dem Kennzeichen {plaka} hat eine "
            "offene Durchfahrt (Fahrzeug ist drinnen).",
        "fr": "Le véhicule immatriculé {plaka} a un passage ouvert "
            "(le véhicule est à l'intérieur).",
        "es": "El vehículo con matrícula {plaka} tiene un pase abierto (el vehículo está dentro).",
    },
    "arac_gecisi_zaten_kapali": {
        "tr": "Araç geçişi zaten kapatılmış.",
        "en": "The vehicle pass has already been closed.",
        "ar": "تم إغلاق تصريح المركبة بالفعل.",
        "ru": "Проезд автомобиля уже закрыт.",
        "de": "Die Fahrzeugdurchfahrt wurde bereits geschlossen.",
        "fr": "Le passage du véhicule a déjà été clôturé.",
        "es": "El pase del vehículo ya fue cerrado.",
    },
    "sakin_daireye_bagli_degil": {
        "tr": "İlişki tipi için sakinin bir daireye bağlı olması gerekir.",
        "en": "The resident must be linked to a unit to set a relationship type.",
        "ar": "يجب ربط الساكن بشقة لتحديد نوع العلاقة.",
        "ru": "Чтобы задать тип отношения, житель должен быть привязан к квартире.",
        "de": "Für die Beziehungsart muss der Bewohner einer Wohnung zugeordnet sein.",
        "fr": "Le résident doit être rattaché à un logement pour définir le type de relation.",
        "es": "El residente debe estar vinculado a una vivienda para definir el tipo de relación.",
    },
    "kamera_restream_semasi": {
        "tr": "Restream adresi http:// veya https:// ile başlamalı.",
        "en": "The restream URL must start with http:// or https://.",
        "ar": "يجب أن يبدأ عنوان إعادة البث بـ http:// أو https://.",
        "ru": "Адрес рестрима должен начинаться с http:// или https://.",
        "de": "Die Restream-Adresse muss mit http:// oder https:// beginnen.",
        "fr": "L’adresse de rediffusion doit commencer par http:// ou https://.",
        "es": "La dirección de retransmisión debe empezar por http:// o https://.",
    },
    # --- ANPR girisi (P16) ---
    "anpr_anahtar_gecersiz": {
        "tr": "ANPR anahtarı geçersiz.",
        "en": "Invalid ANPR key.",
        "ar": "مفتاح ANPR غير صالح.",
        "ru": "Недействительный ключ ANPR.",
        "de": "Ungültiger ANPR-Schlüssel.",
        "fr": "Clé ANPR invalide.",
        "es": "Clave ANPR no válida.",
    },
    "anpr_plaka_bicimi": {
        "tr": "Okunan plaka geçerli biçimde değil.",
        "en": "The plate that was read is not in a valid format.",
        "ar": "اللوحة المقروءة ليست بتنسيق صالح.",
        "ru": "Считанный номер имеет недопустимый формат.",
        "de": "Das gelesene Kennzeichen hat kein gültiges Format.",
        "fr": "La plaque lue n’est pas dans un format valide.",
        "es": "La matrícula leída no tiene un formato válido.",
    },
    "anpr_zaman_bicimi": {
        "tr": "Olay zamanı geçerli biçimde değil.",
        "en": "The event time is not in a valid format.",
        "ar": "وقت الحدث ليس بتنسيق صالح.",
        "ru": "Время события имеет недопустимый формат.",
        "de": "Die Ereigniszeit hat kein gültiges Format.",
        "fr": "L’heure de l’événement n’est pas dans un format valide.",
        "es": "La hora del evento no tiene un formato válido.",
    },
    "anpr_yon_gecersiz": {
        "tr": "Geçiş yönü geçersiz (giris | cikis | bilinmiyor).",
        "en": "Invalid direction (giris | cikis | bilinmiyor).",
        "ar": "اتجاه المرور غير صالح (giris | cikis | bilinmiyor).",
        "ru": "Недопустимое направление (giris | cikis | bilinmiyor).",
        "de": "Ungültige Richtung (giris | cikis | bilinmiyor).",
        "fr": "Direction invalide (giris | cikis | bilinmiyor).",
        "es": "Dirección no válida (giris | cikis | bilinmiyor).",
    },
    "anpr_olay_id_gerekli": {
        "tr": "Kaynak olay kimliği zorunludur.",
        "en": "The source event id is required.",
        "ar": "معرّف حدث المصدر مطلوب.",
        "ru": "Требуется идентификатор события источника.",
        "de": "Die Quell-Ereignis-ID ist erforderlich.",
        "fr": "L’identifiant d’événement source est obligatoire.",
        "es": "El identificador de evento de origen es obligatorio.",
    },
    "anpr_kaynak_bilinmiyor": {
        "tr": "Bilinmeyen ANPR kaynağı.",
        "en": "Unknown ANPR source.",
        "ar": "مصدر ANPR غير معروف.",
        "ru": "Неизвестный источник ANPR.",
        "de": "Unbekannte ANPR-Quelle.",
        "fr": "Source ANPR inconnue.",
        "es": "Fuente ANPR desconocida.",
    },
    "anpr_durum_gecersiz": {
        "tr": "Geçersiz olay durumu süzgeci.",
        "en": "Invalid event status filter.",
        "ar": "مرشّح حالة الحدث غير صالح.",
        "ru": "Недопустимый фильтр статуса события.",
        "de": "Ungültiger Ereignisstatus-Filter.",
        "fr": "Filtre de statut d’événement invalide.",
        "es": "Filtro de estado de evento no válido.",
    },
    "anpr_olay_onay_beklemiyor": {
        "tr": "Bu okuma onay beklemiyor (zaten işlenmiş ya da reddedilmiş).",
        "en": "This reading is not awaiting approval (already processed or rejected).",
        "ar": "هذه القراءة ليست بانتظار الموافقة (تمت معالجتها أو رفضها).",
        "ru": "Это считывание не ожидает подтверждения (уже обработано или отклонено).",
        "de": "Diese Lesung wartet nicht auf Freigabe (bereits verarbeitet oder abgelehnt).",
        "fr": "Cette lecture n’est pas en attente d’approbation (déjà traitée ou refusée).",
        "es": "Esta lectura no está pendiente de aprobación (ya procesada o rechazada).",
    },
    "plaka_bicimi": {
        "tr": "Plaka 2-20 alfanümerik karakter olmalı (örn. 34ABC123).",
        "en": "The plate must be 2-20 alphanumeric characters (e.g. 34ABC123).",
        "ar": "يجب أن تتكون اللوحة من 2 إلى 20 حرفًا ورقمًا (مثال: 34ABC123).",
        "ru": "Номер должен содержать 2–20 буквенно-цифровых символов (например, 34ABC123).",
        "de": "Das Kennzeichen muss 2-20 alphanumerische Zeichen haben (z. B. 34ABC123).",
        "fr": "La plaque doit comporter 2 à 20 caractères alphanumériques (ex. 34ABC123).",
        "es": "La matrícula debe tener entre 2 y 20 caracteres alfanuméricos (p. ej. 34ABC123).",
    },
    "ortak_alan_bulunamadi_veya_pasif": {
        "tr": "Alan bulunamadı veya aktif değil.",
        "en": "The area was not found or is inactive.",
        "ar": "المساحة غير موجودة أو غير نشطة.",
        "ru": "Помещение не найдено или неактивно.",
        "de": "Der Bereich wurde nicht gefunden oder ist inaktiv.",
        "fr": "L'espace est introuvable ou inactif.",
        "es": "El espacio no se encontró o no está activo.",
    },
    "aralik_musaitlik_disinda": {
        "tr": "Seçilen aralık alanın müsaitlik saatleri (açılış-kapanış) dışında.",
        "en": "The selected range is outside the area's availability hours (opening-closing).",
        "ar": "النطاق المحدد خارج ساعات إتاحة المساحة (الفتح والإغلاق).",
        "ru": "Выбранный интервал вне часов доступности помещения (открытие–закрытие).",
        "de": "Der gewählte Zeitraum liegt außerhalb der "
            "Verfügbarkeitszeiten (Öffnung-Schließung).",
        "fr": "La plage sélectionnée est en dehors des heures de "
            "disponibilité (ouverture-fermeture).",
        "es": "El intervalo elegido está fuera del horario de disponibilidad (apertura-cierre).",
    },
    "aktif_daire_baglantiniz_yok": {
        "tr": "Aktif daire bağlantınız yok.",
        "en": "You have no active unit link.",
        "ar": "لا يوجد لديك ارتباط نشط بوحدة.",
        "ru": "У вас нет активной привязки к квартире.",
        "de": "Sie haben keine aktive Zuordnung zu einer Wohneinheit.",
        "fr": "Vous n'avez aucun logement actif associé.",
        "es": "No tiene ninguna vivienda activa vinculada.",
    },
    "unit_id_kendi_daireniz_olmali": {
        "tr": "Seçilen daire kendi daireniz olmalı.",
        "en": "The selected unit must be your own unit.",
        "ar": "يجب أن تكون الوحدة المحددة وحدتك.",
        "ru": "Выбранная квартира должна быть вашей.",
        "de": "Die gewählte Wohneinheit muss Ihre eigene sein.",
        "fr": "Le logement sélectionné doit être le vôtre.",
        "es": "La vivienda seleccionada debe ser la suya.",
    },
    "rezervasyon_cakismasi": {
        "tr": "Seçilen aralık bu alanda onaylanmış bir rezervasyonla çakışıyor.",
        "en": "The selected range conflicts with a confirmed reservation for this area.",
        "ar": "النطاق المحدد يتعارض مع حجز مؤكَّد لهذه المساحة.",
        "ru": "Выбранный интервал пересекается с подтверждённой бронью этого помещения.",
        "de": "Der gewählte Zeitraum überschneidet sich mit einer "
            "bestätigten Reservierung für diesen Bereich.",
        "fr": "La plage sélectionnée est en conflit avec une "
            "réservation confirmée pour cet espace.",
        "es": "El intervalo elegido coincide con una reserva confirmada de este espacio.",
    },
    "rezervasyon_slot_gecti": {
        "tr": "Slot başlangıç saati geçti.",
        "en": "The slot's start time has passed.",
        "ar": "لقد مضى وقت بدء الفترة.",
        "ru": "Время начала слота уже прошло.",
        "de": "Die Startzeit des Zeitfensters ist bereits vorbei.",
        "fr": "L'heure de début du créneau est passée.",
        "es": "La hora de inicio del intervalo ya pasó.",
    },
    "rezervasyon_cok_erken": {
        "tr": "Rezervasyon en erken 24 saat kala yapılabilir.",
        "en": "A reservation can be made at most 24 hours in advance.",
        "ar": "يمكن الحجز قبل 24 ساعة كحد أقصى.",
        "ru": "Бронировать можно не ранее чем за 24 часа.",
        "de": "Eine Reservierung ist frühestens 24 Stunden vorher möglich.",
        "fr": "Une réservation peut être faite au plus tôt 24 heures à l'avance.",
        "es": "La reserva se puede hacer como máximo 24 horas antes.",
    },
    "rezervasyon_gunluk_kota": {
        "tr": "Bu gün için zaten bir rezervasyonunuz var.",
        "en": "You already have a reservation for this day.",
        "ar": "لديك بالفعل حجز في هذا اليوم.",
        "ru": "У вас уже есть бронирование на этот день.",
        "de": "Sie haben für diesen Tag bereits eine Reservierung.",
        "fr": "Vous avez déjà une réservation pour ce jour.",
        "es": "Ya tiene una reserva para este día.",
    },
    "rezervasyon_zaten_iptal": {
        "tr": "Rezervasyon zaten iptal edilmiş.",
        "en": "The reservation has already been cancelled.",
        "ar": "تم إلغاء الحجز بالفعل.",
        "ru": "Бронирование уже отменено.",
        "de": "Die Reservierung wurde bereits storniert.",
        "fr": "La réservation a déjà été annulée.",
        "es": "La reserva ya fue cancelada.",
    },
    "rezervasyon_iptal_icin_gec": {
        "tr": "Rezervasyon başlangıcına 10 dakikadan az kaldı, iptal edilemez.",
        "en": "Less than 10 minutes remain before the reservation starts; it cannot be cancelled.",
        "ar": "بقي أقل من 10 دقائق على بدء الحجز؛ لا يمكن إلغاؤه.",
        "ru": "До начала бронирования осталось менее 10 минут — отменить нельзя.",
        "de": "Bis zum Beginn der Reservierung bleiben weniger als 10 "
            "Minuten; sie kann nicht storniert werden.",
        "fr": "Il reste moins de 10 minutes avant le début de la "
            "réservation ; elle ne peut pas être annulée.",
        "es": "Faltan menos de 10 minutos para el inicio de la reserva; no se puede cancelar.",
    },
    "ortak_alan_adi_zaten_var": {
        "tr": "Bu adla bir ortak alan zaten var.",
        "en": "A common area with this name already exists.",
        "ar": "توجد مساحة مشتركة بهذا الاسم بالفعل.",
        "ru": "Общее помещение с таким названием уже существует.",
        "de": "Ein Gemeinschaftsbereich mit diesem Namen existiert bereits.",
        "fr": "Un espace commun portant ce nom existe déjà.",
        "es": "Ya existe una zona común con ese nombre.",
    },
    "kapanis_acilistan_sonra": {
        "tr": "Kapanış saati açılıştan sonra olmalı.",
        "en": "The closing time must be after the opening time.",
        "ar": "يجب أن يكون وقت الإغلاق بعد وقت الفتح.",
        "ru": "Время закрытия должно быть позже времени открытия.",
        "de": "Die Schließzeit muss nach der Öffnungszeit liegen.",
        "fr": "L'heure de fermeture doit être postérieure à l'ouverture.",
        "es": "La hora de cierre debe ser posterior a la de apertura.",
    },
    "bitis_baslangictan_sonra": {
        "tr": "Bitiş zamanı başlangıçtan sonra olmalı.",
        "en": "The end time must be after the start time.",
        "ar": "يجب أن يكون وقت الانتهاء بعد وقت البدء.",
        "ru": "Время окончания должно быть позже времени начала.",
        "de": "Die Endzeit muss nach der Startzeit liegen.",
        "fr": "L'heure de fin doit être postérieure à l'heure de début.",
        "es": "La hora de fin debe ser posterior a la de inicio.",
    },
    "rsvp_degistirilemez": {
        "tr": "Katılım beyanınız kaydedildi; değiştirilemez.",
        "en": "Your RSVP has been recorded and cannot be changed.",
        "ar": "تم تسجيل ردّك على الدعوة ولا يمكن تغييره.",
        "ru": "Ваш ответ об участии сохранён и не может быть изменён.",
        "de": "Ihre Teilnahmeangabe wurde gespeichert und kann nicht geändert werden.",
        "fr": "Votre réponse de participation a été enregistrée et ne peut pas être modifiée.",
        "es": "Su confirmación de asistencia se guardó y no se puede cambiar.",
    },
    "sikayet_yalniz_kendi_blok": {
        "tr": "Yalnızca kendi bloğunuzdaki daireleri şikayet edebilirsiniz.",
        "en": "You can only file complaints about units in your own block.",
        "ar": "يمكنك تقديم شكاوى بشأن الوحدات في مبناك فقط.",
        "ru": "Вы можете жаловаться только на квартиры в своём блоке.",
        "de": "Sie können sich nur über Wohneinheiten in Ihrem eigenen Block beschweren.",
        "fr": "Vous ne pouvez signaler que des logements de votre propre bloc.",
        "es": "Solo puede presentar quejas sobre viviendas de su propio bloque.",
    },
    "sikayet_haftalik_limit": {
        "tr": "Bu daire için bu konuda haftada en fazla 1 şikayet açabilirsiniz.",
        "en": "You can file at most 1 complaint per week about this unit on this topic.",
        "ar": "يمكنك تقديم شكوى واحدة كحد أقصى أسبوعيًا بشأن هذه الوحدة في هذا الموضوع.",
        "ru": "По этой теме можно подать не более 1 жалобы в неделю на эту квартиру.",
        "de": "Sie können zu diesem Thema höchstens 1 Beschwerde pro "
            "Woche zu dieser Wohneinheit einreichen.",
        "fr": "Vous pouvez déposer au maximum 1 signalement par "
            "semaine sur ce sujet pour ce logement.",
        "es": "Puede presentar como máximo 1 queja por semana sobre esta vivienda en este tema.",
    },
    "talep_zaten_yanitlanmis": {
        "tr": "Talep zaten yanıtlanmış (ilk karar geçerli).",
        "en": "The request has already been answered (the first decision stands).",
        "ar": "تمت الإجابة على الطلب بالفعل (القرار الأول هو المعتمد).",
        "ru": "Заявка уже рассмотрена (действует первое решение).",
        "de": "Der Antrag wurde bereits beantwortet (die erste Entscheidung gilt).",
        "fr": "La demande a déjà reçu une réponse (la première décision prévaut).",
        "es": "La solicitud ya fue respondida (vale la primera decisión).",
    },
    "gecersiz_durum_gecisi": {
        "tr": "'{mevcut}' → '{hedef}' geçersiz durum geçişi.",
        "en": "'{mevcut}' → '{hedef}' is an invalid status transition.",
        "ar": "الانتقال من '{mevcut}' إلى '{hedef}' غير صالح.",
        "ru": "Переход '{mevcut}' → '{hedef}' недопустим.",
        "de": "'{mevcut}' → '{hedef}' ist ein ungültiger Statuswechsel.",
        "fr": "'{mevcut}' → '{hedef}' est une transition de statut invalide.",
        "es": "'{mevcut}' → '{hedef}' es una transición de estado no válida.",
    },
    "tahakkuk_zaten_var": {
        "tr": "Bu daire için bu dönem tahakkuk zaten var.",
        "en": "An assessment already exists for this unit and period.",
        "ar": "يوجد بالفعل استحقاق لهذه الوحدة وهذه الفترة.",
        "ru": "Начисление для этой квартиры и периода уже существует.",
        "de": "Für diese Wohneinheit und diesen Zeitraum existiert bereits eine Sollstellung.",
        "fr": "Un appel de charges existe déjà pour ce logement et cette période.",
        "es": "Ya existe un cargo para esta vivienda y período.",
    },
    "tahakkuk_bulunamadi": {
        "tr": "Tahakkuk bu tesiste bulunamadı.",
        "en": "The assessment was not found in this facility.",
        "ar": "لم يتم العثور على الاستحقاق في هذه المنشأة.",
        "ru": "Начисление не найдено в этом объекте.",
        "de": "Die Sollstellung wurde in dieser Anlage nicht gefunden.",
        "fr": "L'appel de charges est introuvable dans cet établissement.",
        "es": "No se encontró el cargo en esta instalación.",
    },
    "butce_kategori_bulunamadi": {
        "tr": "Kategori bu tesiste bulunamadı.",
        "en": "The category was not found in this facility.",
        "ar": "لم يتم العثور على الفئة في هذه المنشأة.",
        "ru": "Категория не найдена в этом объекте.",
        "de": "Die Kategorie wurde in dieser Anlage nicht gefunden.",
        "fr": "La catégorie est introuvable dans cet établissement.",
        "es": "No se encontró la categoría en esta instalación.",
    },
    "butce_kategori_ad_tip_var": {
        "tr": "Bu ad ve tipte kategori zaten var.",
        "en": "A category with this name and type already exists.",
        "ar": "توجد فئة بهذا الاسم والنوع بالفعل.",
        "ru": "Категория с таким названием и типом уже существует.",
        "de": "Eine Kategorie mit diesem Namen und Typ existiert bereits.",
        "fr": "Une catégorie avec ce nom et ce type existe déjà.",
        "es": "Ya existe una categoría con ese nombre y tipo.",
    },
    "butce_pasif_kategoriye_yazilamaz": {
        "tr": "Pasif kategoriye yeni kayıt yazılamaz (kategoriyi aktifleştirin).",
        "en": "New entries cannot be added to an inactive category (activate the category).",
        "ar": "لا يمكن إضافة قيود جديدة إلى فئة غير نشطة (فعّل الفئة).",
        "ru": "В неактивную категорию нельзя добавлять записи (активируйте категорию).",
        "de": "In einer inaktiven Kategorie können keine neuen Einträge "
            "angelegt werden (Kategorie aktivieren).",
        "fr": "Impossible d'ajouter des écritures à une catégorie inactive (activez la catégorie).",
        "es": "No se pueden añadir apuntes a una categoría inactiva (active la categoría).",
    },
    "butce_pasif_kategoriye_tasinamaz": {
        "tr": "Pasif kategoriye taşınamaz.",
        "en": "It cannot be moved to an inactive category.",
        "ar": "لا يمكن نقله إلى فئة غير نشطة.",
        "ru": "Нельзя перенести в неактивную категорию.",
        "de": "Eine Verschiebung in eine inaktive Kategorie ist nicht möglich.",
        "fr": "Impossible de le déplacer vers une catégorie inactive.",
        "es": "No se puede mover a una categoría inactiva.",
    },
    "butce_otomatik_aidat_kaydi": {
        "tr": "Otomatik aidat kaydı düzenlenemez/silinemez; aidat modülünden yönetilir.",
        "en": "Automatic dues entries cannot be edited or deleted; "
            "manage them from the dues module.",
        "ar": "لا يمكن تعديل أو حذف قيد الرسوم التلقائي؛ يُدار من وحدة الرسوم.",
        "ru": "Автоматическую запись взносов нельзя изменить или "
            "удалить — управляйте ею в модуле взносов.",
        "de": "Automatische Beitragsbuchungen können nicht bearbeitet oder "
            "gelöscht werden; verwalten Sie sie im Beitragsmodul.",
        "fr": "Les écritures de charges automatiques ne peuvent être ni modifiées ni "
            "supprimées ; gérez-les depuis le module des charges.",
        "es": "Los apuntes automáticos de cuotas no se pueden editar ni "
            "eliminar; gestiónelos desde el módulo de cuotas.",
    },
    "donem_bicimi": {
        "tr": "Dönem 'YYYY-AA' biçiminde olmalı.",
        "en": "The period must be in 'YYYY-MM' format.",
        "ar": "يجب أن تكون الفترة بصيغة 'YYYY-MM'.",
        "ru": "Период должен быть в формате «YYYY-MM».",
        "de": "Der Zeitraum muss im Format 'YYYY-MM' angegeben werden.",
        "fr": "La période doit être au format « YYYY-MM ».",
        "es": "El período debe tener el formato «YYYY-MM».",
    },
    "ay_bicimi": {
        "tr": "Ay 'YYYY-AA' biçiminde olmalı.",
        "en": "The month must be in 'YYYY-MM' format.",
        "ar": "يجب أن يكون الشهر بصيغة 'YYYY-MM'.",
        "ru": "Месяц должен быть в формате «YYYY-MM».",
        "de": "Der Monat muss im Format 'YYYY-MM' angegeben werden.",
        "fr": "Le mois doit être au format « YYYY-MM ».",
        "es": "El mes debe tener el formato «YYYY-MM».",
    },
    "ihlal_yeniden_acilamaz": {
        "tr": "Kapatılmış ihlal yeniden açılamaz.",
        "en": "A closed violation cannot be reopened.",
        "ar": "لا يمكن إعادة فتح مخالفة مغلقة.",
        "ru": "Закрытое нарушение нельзя открыть заново.",
        "de": "Ein geschlossener Verstoß kann nicht wieder geöffnet werden.",
        "fr": "Une infraction clôturée ne peut pas être rouverte.",
        "es": "Una infracción cerrada no se puede reabrir.",
    },
    "ihlal_yalniz_admin_kapatir": {
        "tr": "İhlali yalnız yönetici kapatabilir.",
        "en": "Only an admin can close a violation.",
        "ar": "لا يمكن إغلاق المخالفة إلا من قبل المشرف.",
        "ru": "Закрыть нарушение может только администратор.",
        "de": "Nur ein Administrator kann einen Verstoß schließen.",
        "fr": "Seul un administrateur peut clôturer une infraction.",
        "es": "Solo un administrador puede cerrar una infracción.",
    },
    "seffaflik_yayin_yok": {
        "tr": "Bu ay için yayınlanmış özet yok.",
        "en": "No published summary for this month.",
        "ar": "لا يوجد ملخص منشور لهذا الشهر.",
        "ru": "За этот месяц нет опубликованной сводки.",
        "de": "Für diesen Monat wurde keine Zusammenfassung veröffentlicht.",
        "fr": "Aucun résumé publié pour ce mois.",
        "es": "No hay resumen publicado para este mes.",
    },
    "foto_key_alan_disi": {
        "tr": "Fotoğraf anahtarı bu tesisin alanı dışında.",
        "en": "The photo key is outside this facility's namespace.",
        "ar": "مفتاح الصورة خارج نطاق هذه المنشأة.",
        "ru": "Ключ фотографии вне пространства имён этого объекта.",
        "de": "Der Foto-Schlüssel liegt außerhalb des Namensraums dieser Anlage.",
        "fr": "La clé photo est en dehors de l'espace de cet établissement.",
        "es": "La clave de la foto está fuera del espacio de esta instalación.",
    },
    "avatar_key_alan_disi": {
        "tr": "Profil fotoğrafı anahtarı bu tesisin alanı dışında.",
        "en": "The avatar key is outside this facility's namespace.",
        "ar": "مفتاح صورة الملف الشخصي خارج نطاق هذه المنشأة.",
        "ru": "Ключ аватара вне пространства имён этого объекта.",
        "de": "Der Avatar-Schlüssel liegt außerhalb des Namensraums dieser Anlage.",
        "fr": "La clé de l'avatar est en dehors de l'espace de cet établissement.",
        "es": "La clave del avatar está fuera del espacio de esta instalación.",
    },
    "kamera_url_cok_uzun": {
        "tr": "Yayın adresi çok uzun ({uzunluk} karakter); en fazla {sinir} olabilir.",
        "en": "The stream URL is too long ({uzunluk} characters); the maximum is {sinir}.",
        "ar": "عنوان البث طويل جدًا ({uzunluk} حرفًا)؛ الحد الأقصى {sinir}.",
        "ru": "Адрес потока слишком длинный ({uzunluk} символов); максимум — {sinir}.",
        "de": "Die Stream-Adresse ist zu lang ({uzunluk} Zeichen); maximal {sinir}.",
        "fr": "L'adresse du flux est trop longue ({uzunluk} caractères) ; maximum {sinir}.",
        "es": "La dirección de emisión es demasiado larga ({uzunluk} caracteres); el máximo es {sinir}.",
    },
    "kamera_url_semasi": {
        "tr": "{tur} türü için yayın adresi {semalar} ile başlamalı.",
        "en": "For type {tur}, the stream URL must start with {semalar}.",
        "ar": "بالنسبة للنوع {tur}، يجب أن يبدأ عنوان البث بـ {semalar}.",
        "ru": "Для типа {tur} адрес потока должен начинаться с {semalar}.",
        "de": "Für den Typ {tur} muss die Stream-Adresse mit {semalar} beginnen.",
        "fr": "Pour le type {tur}, l'adresse du flux doit commencer par {semalar}.",
        "es": "Para el tipo {tur}, la dirección de emisión debe empezar por {semalar}.",
    },
    "destek_bileti_bulunamadi": {
        "tr": "Destek bileti bulunamadı.",
        "en": "Support ticket not found.",
        "ar": "لم يتم العثور على تذكرة الدعم.",
        "ru": "Обращение в поддержку не найдено.",
        "de": "Support-Ticket nicht gefunden.",
        "fr": "Ticket d'assistance introuvable.",
        "es": "No se encontró el ticket de soporte.",
    },
    "destek_guncelleme_alani_gerekli": {
        "tr": "Durum, yanıt veya fotoğraf alanlarından en az biri gerekli.",
        "en": "At least one of status, reply or photo is required.",
        "ar": "مطلوب واحد على الأقل من: الحالة أو الرد أو الصورة.",
        "ru": "Требуется хотя бы одно из полей: статус, ответ или фото.",
        "de": "Mindestens eines der Felder Status, Antwort oder Foto ist erforderlich.",
        "fr": "Au moins l'un des champs statut, réponse ou photo est requis.",
        "es": "Se requiere al menos uno de los campos: estado, respuesta o foto.",
    },
    "aktif_cihaz_bulunamadi": {
        "tr": "Aktif cihaz bulunamadı.",
        "en": "No active device found.",
        "ar": "لم يتم العثور على جهاز نشط.",
        "ru": "Активное устройство не найдено.",
        "de": "Kein aktives Gerät gefunden.",
        "fr": "Aucun appareil actif trouvé.",
        "es": "No se encontró ningún dispositivo activo.",
    },
    "arama_rol_yetkisi_yok": {
        "tr": "Bu rolü arama yetkiniz yok.",
        "en": "You are not allowed to call this role.",
        "ar": "لا تملك صلاحية الاتصال بهذا الدور.",
        "ru": "У вас нет права звонить этой роли.",
        "de": "Sie dürfen diese Rolle nicht anrufen.",
        "fr": "Vous n'êtes pas autorisé à appeler ce rôle.",
        "es": "No tiene permiso para llamar a este rol.",
    },
    "kullanici_su_an_aranamiyor": {
        "tr": "Bu kullanıcı şu an aranamıyor.",
        "en": "This user cannot be called right now.",
        "ar": "لا يمكن الاتصال بهذا المستخدم الآن.",
        "ru": "Сейчас этому пользователю нельзя позвонить.",
        "de": "Dieser Benutzer kann derzeit nicht angerufen werden.",
        "fr": "Cet utilisateur ne peut pas être appelé pour le moment.",
        "es": "No se puede llamar a este usuario en este momento.",
    },
    "hava_durumu_alinamiyor": {
        "tr": "Hava durumu şu an alınamıyor.",
        "en": "Weather data is not available right now.",
        "ar": "تعذّر الحصول على حالة الطقس الآن.",
        "ru": "Данные о погоде сейчас недоступны.",
        "de": "Wetterdaten sind derzeit nicht verfügbar.",
        "fr": "Les données météo ne sont pas disponibles pour le moment.",
        "es": "Ahora mismo no se puede obtener la información del tiempo.",
    },
    "cursor_gecersiz": {
        "tr": "Geçersiz sayfa imleci.",
        "en": "Invalid page cursor.",
        "ar": "مؤشر صفحة غير صالح.",
        "ru": "Недействительный курсор страницы.",
        "de": "Ungültiger Seiten-Cursor.",
        "fr": "Curseur de page invalide.",
        "es": "Cursor de página no válido.",
    },
    "odeme_bulunamadi": {
        "tr": "Ödeme bulunamadı.",
        "en": "Payment not found.",
        "ar": "لم يتم العثور على الدفعة.",
        "ru": "Платёж не найден.",
        "de": "Zahlung nicht gefunden.",
        "fr": "Paiement introuvable.",
        "es": "Pago no encontrado.",
    },
    "odeme_referansi_bulunamadi": {
        "tr": "Ödeme referansı bulunamadı.",
        "en": "Payment reference not found.",
        "ar": "لم يتم العثور على مرجع الدفع.",
        "ru": "Ссылка на платёж не найдена.",
        "de": "Zahlungsreferenz nicht gefunden.",
        "fr": "Référence de paiement introuvable.",
        "es": "No se encontró la referencia de pago.",
    },
    "webhook_tutar_uyusmuyor": {
        "tr": "Bildirim tutarı ödeme ile uyuşmuyor.",
        "en": "The webhook amount does not match the payment.",
        "ar": "مبلغ الإشعار لا يطابق الدفعة.",
        "ru": "Сумма уведомления не совпадает с платежом.",
        "de": "Der Betrag der Benachrichtigung stimmt nicht mit der Zahlung überein.",
        "fr": "Le montant de la notification ne correspond pas au paiement.",
        "es": "El importe de la notificación no coincide con el pago.",
    },
    "webhook_imza_gecersiz": {
        "tr": "{saglayici} bildirim imzası geçersiz.",
        "en": "The {saglayici} webhook signature is invalid.",
        "ar": "توقيع إشعار {saglayici} غير صالح.",
        "ru": "Подпись webhook {saglayici} недействительна.",
        "de": "Die {saglayici}-Webhook-Signatur ist ungültig.",
        "fr": "La signature du webhook {saglayici} est invalide.",
        "es": "La firma del webhook de {saglayici} no es válida.",
    },
    "bilinmeyen_odeme_saglayicisi": {
        "tr": "Bilinmeyen ödeme sağlayıcısı: {saglayici}",
        "en": "Unknown payment provider: {saglayici}",
        "ar": "مزود دفع غير معروف: {saglayici}",
        "ru": "Неизвестный платёжный провайдер: {saglayici}",
        "de": "Unbekannter Zahlungsanbieter: {saglayici}",
        "fr": "Fournisseur de paiement inconnu : {saglayici}",
        "es": "Proveedor de pago desconocido: {saglayici}",
    },
}
